# Generated by Django 5.0.6 on 2024-08-21 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_servicetype_alter_problemreport_citizen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemreport',
            name='description',
            field=models.TextField(default='Need help'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='description',
            field=models.TextField(default='Need help'),
        ),
    ]
