# Generated by Django 5.1.1 on 2024-10-18 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_problemreport_description_servicerequest_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemtype',
            name='image',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='image',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
